services:
  - type: web
    name: notifica-fe
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        value: "http://localhost:8080"
      - key: VITE_CLERK_PUBLISHABLE_KEY
        value: "pk_test_Y29tcGxldGUtY2F0dGxlLTgwLmNsZXJrLmFjY291bnRzLmRldiQ"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
