version: "3.8"
services:
  backend:
    platform: linux/arm64
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
