version: "3.8"
services:
  backend:
    build:
      context: ..
      dockerfile: BE/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=${MONGODB_URI}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - FRONTEND_URL=http://localhost:5173
    volumes:
      - ./BE:/usr/src/app/src
      - be_node_modules:/usr/src/app/node_modules
    command: npm run dev
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  be_node_modules:
